apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  {{- with .Values.common.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ .Values.app.name}}
  ports:
  - protocol: "TCP"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.target_port }}
  type: LoadBalancer